
export enum LinkName {
  SUCCESS = 'SUCCESS',
  CANCEL = 'CANCEL',
  ICON = 'ICON',
  IMAGE = 'IMAGE',
  WHATSAPP = 'WHATSAPP',
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  TWITTER = 'TWITTER',
  PAGE_GUIDE = 'PAGE_GUIDE',
  STORE_LINK = 'STORE_LINK',
  OTHER = 'OTHER'
}